defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: "[ -d node_modules ] || npm i"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build dist
          command: npm run build
      - save_cache:
          key: build-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./dist
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published

workflows:
  version: 2
  delivery:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - publish:
          context: org-global
          requires:
            - build